### ISSUE TITLE
ReadingPage

### ISSUE THREAD

**Issue by louisweiser** [louisweiser/project_capstone#11]
## Value Proposition

As a User :
I would like to have a page that displays all of the notes I have made about my books.

## Description

![Image](https://user-images.githubusercontent.com/122813337/229307964-c3b4ada9-817f-4788-aa05-701dcccfb6a2.png)

## Acceptance Criteria

- [ ] All quotes and stories should be listed in a list
- [ ] Each entry should take up a visual field
- [ ] Only a maximum of 10 entries should be rendered at a time to maintain stable performance
- [ ] When scrolling, the entries should be automatically generated

## Tasks

- [ ] Create a component that will render the entries for the notes page.
- [ ] Import the necessary data, such as the list of quotes and stories, into the component.
- [ ] Create a function that can dynamically render the entries based on the data.
- [ ] Implement any necessary styling or visual elements to display each entry as a separate visual field.
      ​

## Complexity

M

**Comment by rabe200** [comment]
lgtm
