### ISSUE TITLE
Search in ReadingPage

### ISSUE THREAD

**Issue by louisweiser** [louisweiser/project_capstone#12]
## Value Proposition

As a User :
I would like the ability to quickly find specific entries on the reading page through a search feature. The search should be fast and easily accessible.

## Description

![Image](https://user-images.githubusercontent.com/122813337/229308700-1d180039-4ae2-4d86-8c88-e591d729d568.png)

## Acceptance Criteria

- [ ] There is a search bar located at the very top of the reading page
- [ ] When a search query is entered, the content on the page should adjust to reflect the search criteria
- [ ] It should be possible to end the search and return to the original state.

## Tasks

- [ ] Create a search component.
- [ ] Create a form within the search component.
- [ ] Use a global state for the search term.
- [ ] Implement the logic in the form to save the inputs.
- [ ] Implement the search filter in the rendering of the page.
      ​

## Complexity

M
