### ISSUE TITLE
CreatePage

### ISSUE THREAD

**Issue by louisweiser** [louisweiser/project_capstone#15]
## Value Proposition

As a User :
I would like to be able to create entries for my books in the library.

## Description

![Image](https://user-images.githubusercontent.com/122813337/229309157-5322d97b-55f9-42b6-81bd-4b3dd2ac0566.png)

## Acceptance Criteria

- [ ] There should be a field for the headline.
- [ ] There should be a text field.
- [ ] There should be a field for entering the page number.
- [ ] It should be possible to submit the entries.
- [ ] The button should display the book cover for which the entry is being added.

## Tasks

- [ ] build a form component
- [ ] Implement the headline input for the entry.
- [ ] Implement the text input for the entry.
- [ ] Implement the page input for the entry.
- [ ] Implement a button to save the entry.
- [ ] Implement the logic to save the data for the entry.
- [ ] Implement the logic to pass the data to the database.

## Complexity

XL
