### ISSUE TITLE
HomePage

### ISSUE THREAD

**Issue by louisweiser** [louisweiser/project_capstone#8]
## Value Proposition

As a User :
I would like to get an overview of the application. What is the benefit of the app? What does it include? What functions does it have? The homepage should display a random note from the library.

## Description

![Image](https://user-images.githubusercontent.com/122813337/229302150-c6947b8b-2ab6-4960-b2bb-b48df4a71484.png)

## Acceptance Criteria

- [ ] There is a viewbox for a random note that changes daily.
- [ ] There is headline, that show the app title.
- [ ] There is a SVG background, which look like wood structure

## Tasks

- [ ] build a Header component
- [ ] header component has a background
- [ ] header component show bookLog
- [ ] built a component for the random note
- [ ] implement logic for random note
- [ ] bulit a background component
- [ ] the background component make a dynamic SVG by view width
      ​

## Complexity

M

**Comment by nikokreissl** [comment]
Good work and a lot of information, very nice! 🙂
Two things came up to my mind when reading this us:
1. At value proposition I would keep it a little bit shorter like "... I want to see a viewbox on the homepage which gives some hints so that I know what the app is about". The items you listed for me suit better to description.
2. at acceptance criteria I would add that it is about the homepage (if I got that correctly from value proposition) and I would not use "SVG" as a word because none-tech people won't know what it is about 😉 instead I would just say "A wood structure background is shown"

**Comment by louisweiser** [comment]
Thank you, Niko, for your detailed feedback. I think you are right. Your opinion is very helpful.
