### ISSUE TITLE
LibraryPage

### ISSUE THREAD

**Issue by louisweiser** [louisweiser/project_capstone#9]
## Value Proposition

As a User :
I want to have an overview of all the books in my library. The books should be arranged clearly so that I can navigate easily. Only the covers should be visible. Additionally, the background should have a nice structure.

## Description

![Image](https://user-images.githubusercontent.com/122813337/229304011-24798d98-ff76-4edd-a100-6181029cb80d.png)

## Acceptance Criteria

- [ ] There is an SVG background that looks like a wood structure
- [ ] The books are represented by their covers
- [ ] The covers all have the same height and are not distorted or cropped
- [ ] The books are categorized by genre
- [ ] The books are arranged side by side
- [ ] When the screen is exceeded, the books can be scrolled horizontally

## Tasks

- [ ] Implement the dynamic background component
- [ ] Create an API query that can determine the dimensions of the covers
- [ ] Create a component that can dynamically generate the book covers
- [ ] Create a component that can dynamically render the entire library
- [ ] implement all components in the library page
      ​

## Complexity

XXL
